/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superpuissance4_perello_lamassiaude;

import java.util.Scanner;


/**
 *
 * @author Acer
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    Joueur[] ListeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Grille grilleJeu = new Grille();

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        Panneau_info_Joueurs.setVisible(false);
        Panneau_info_Partie.setVisible(false);
        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.Cellules[i][j]);
                PanneauGrille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        Panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomJoueur1 = new javax.swing.JTextField();
        nomJoueur2 = new javax.swing.JTextField();
        btn_Start = new javax.swing.JButton();
        Panneau_info_Joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_J2_desintegrateur = new javax.swing.JLabel();
        lbl_J2_nom = new javax.swing.JLabel();
        lbl_J2_couleur = new javax.swing.JLabel();
        lbl_J1_nom = new javax.swing.JLabel();
        lbl_J1_couleur1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_J1_desintegrateur1 = new javax.swing.JLabel();
        Panneau_info_Partie = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_JCourant = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        btn_Col_0 = new javax.swing.JButton();
        btn_Col_1 = new javax.swing.JButton();
        btn_Col_2 = new javax.swing.JButton();
        btn_Col_3 = new javax.swing.JButton();
        btn_Col_4 = new javax.swing.JButton();
        btn_Col_5 = new javax.swing.JButton();
        btn_Col_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 255, 255));
        PanneauGrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 672, 576));

        Panneau_creation_partie.setBackground(new java.awt.Color(204, 255, 204));
        Panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2 :");
        Panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Nom Joueur 1 :");
        Panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        nomJoueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur1ActionPerformed(evt);
            }
        });
        Panneau_creation_partie.add(nomJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 30));

        nomJoueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur2ActionPerformed(evt);
            }
        });
        Panneau_creation_partie.add(nomJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 30));

        btn_Start.setText("Démarrer Partie");
        btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StartActionPerformed(evt);
            }
        });
        Panneau_creation_partie.add(btn_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));

        getContentPane().add(Panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 360, 130));

        Panneau_info_Joueurs.setBackground(new java.awt.Color(204, 255, 204));
        Panneau_info_Joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Info Joueurs:");
        Panneau_info_Joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Joueur 2:");
        Panneau_info_Joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("Couleur:");
        Panneau_info_Joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setText("Désintégrateurs : ");
        Panneau_info_Joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel7.setText("Joueur 1 :");
        Panneau_info_Joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel8.setText("Couleur :");
        Panneau_info_Joueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setText("Désintégrateurs : ");
        Panneau_info_Joueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lbl_J2_desintegrateur.setText("nbDesinteJoueur2");
        Panneau_info_Joueurs.add(lbl_J2_desintegrateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        lbl_J2_nom.setText("nomJoueur2");
        Panneau_info_Joueurs.add(lbl_J2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        lbl_J2_couleur.setText("couleurJoueur2");
        Panneau_info_Joueurs.add(lbl_J2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        lbl_J1_nom.setText("nomJoueur1");
        Panneau_info_Joueurs.add(lbl_J1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lbl_J1_couleur1.setText("couleurJoueur1");
        Panneau_info_Joueurs.add(lbl_J1_couleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));
        Panneau_info_Joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 320, 30));

        lbl_J1_desintegrateur1.setText("nbDesinteJoueur1");
        Panneau_info_Joueurs.add(lbl_J1_desintegrateur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        getContentPane().add(Panneau_info_Joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 360, 240));

        Panneau_info_Partie.setBackground(new java.awt.Color(204, 255, 204));
        Panneau_info_Partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Info Jeu:");
        Panneau_info_Partie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_JCourant.setText("nomJoueur");
        Panneau_info_Partie.add(lbl_JCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel12.setText("Joueur Courant :");
        Panneau_info_Partie.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        Panneau_info_Partie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 80));

        getContentPane().add(Panneau_info_Partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 360, 160));

        btn_Col_0.setText("7");
        getContentPane().add(btn_Col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, -1, -1));

        btn_Col_1.setText("1");
        getContentPane().add(btn_Col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btn_Col_2.setText("2");
        getContentPane().add(btn_Col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 20, -1, -1));

        btn_Col_3.setText("3");
        getContentPane().add(btn_Col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 20, -1, -1));

        btn_Col_4.setText("4");
        getContentPane().add(btn_Col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, -1, -1));

        btn_Col_5.setText("5");
        getContentPane().add(btn_Col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 20, -1, -1));

        btn_Col_6.setText("6");
        btn_Col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartActionPerformed
        // TODO add your handling code here:
        Panneau_info_Joueurs.setVisible(true);
        Panneau_info_Partie.setVisible(true);
        initialiserPartie();
        PanneauGrille.repaint();
        btn_Start.setEnabled(false);
    }//GEN-LAST:event_btn_StartActionPerformed

    private void nomJoueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJoueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomJoueur1ActionPerformed

    private void nomJoueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJoueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomJoueur2ActionPerformed

    private void btn_Col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Col_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Col_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    void initialiserPartie(){
    //inscription des 2 joueurs:
    String Joueur1=nomJoueur1.getText();
    String Joueur2=nomJoueur2.getText();
    Joueur J1 = new Joueur(Joueur1);
    Joueur J2 = new Joueur(Joueur2);
    ListeJoueurs[0]=J1;
    ListeJoueurs[1]=J2;
    
    lbl_J1_nom.setText(Joueur1);
    lbl_J2_nom.setText(Joueur2);
    
    //détermination du 1er joueur:
    double nbalea=Math.random();
    if (nbalea>0.5) {
        joueurCourant= ListeJoueurs[0];
    }
    else{
        joueurCourant= ListeJoueurs[1];
    }
    lbl_JCourant.setText(joueurCourant.Nom);
    System.out.println("Le premier joueur est : "+joueurCourant.Nom);
    
    //Distribution des couleurs:
    attribuerCouleursAuxJoueurs();
    
    lbl_J1_couleur1.setText(J1.Couleur);
    lbl_J2_couleur.setText(J2.Couleur);
    
    
    lbl_J1_desintegrateur1.setText(J1.nombreDesintegrateurs+"");
    lbl_J2_desintegrateur.setText(J2.nombreDesintegrateurs+"");
    
    //Création de la grille
    grilleJeu.viderGrille();
    int nbTN=0;
    while (nbTN<=4){
        int ligne=(int)(Math.random() * 6);
        int colone=(int)(Math.random() * 7);
        if (grilleJeu.Cellules[ligne][colone].desintegrateur==false && grilleJeu.Cellules[ligne][colone].trouNoir==false){
            if (nbTN==3 || nbTN==4){
                grilleJeu.placerTrouNoir(ligne,colone);
                grilleJeu.placerDesintegrateur(ligne,colone);
            }else{
                grilleJeu.placerTrouNoir(ligne,colone);
            }
            nbTN+=1;
    }
    }
    int nbDesint=0;
    while (nbDesint<=2){
        int ligne=(int)(Math.random() * 6);
        int colone=(int)(Math.random() * 7);
        if (grilleJeu.Cellules[ligne][colone].desintegrateur==false && grilleJeu.Cellules[ligne][colone].trouNoir==false){
            grilleJeu.placerDesintegrateur(ligne,colone);
            nbDesint+=1;
        }else{
                nbDesint=nbDesint;
                }
    }    
    for (int i=0;i<21;i++){
        if (ListeJoueurs[0].Couleur.equals("Rouge")){
            Jeton jetonjoueurR = new Jeton("Rouge");
            ListeJoueurs[0].ajouterJeton(jetonjoueurR);
            Jeton jetonjoueurJ = new Jeton("Jaune");
            ListeJoueurs[1].ajouterJeton(jetonjoueurJ);
        }else{
            Jeton jetonjoueurR = new Jeton("Rouge");
            ListeJoueurs[1].ajouterJeton(jetonjoueurR);
            Jeton jetonjoueurJ = new Jeton("Jaune");
            ListeJoueurs[0].ajouterJeton(jetonjoueurJ);
        }
    }
}
    
    void attribuerCouleursAuxJoueurs(){
    double nbalea=Math.random();
    if (nbalea>0.5) {
        ListeJoueurs[0].affecterCouleur("Rouge");
        ListeJoueurs[1].affecterCouleur("Jaune");
        System.out.println(ListeJoueurs[0].Nom+" a la couleur ROUGE");
        System.out.println(ListeJoueurs[1].Nom+" a la couleur JAUNE");
    }else{
        ListeJoueurs[0].affecterCouleur("Jaune");
        ListeJoueurs[1].affecterCouleur("Rouge");
        System.out.println(ListeJoueurs[1].Nom+" a la couleur ROUGE");
        System.out.println(ListeJoueurs[0].Nom+" a la couleur JAUNE");
    }
}

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel Panneau_creation_partie;
    private javax.swing.JPanel Panneau_info_Joueurs;
    private javax.swing.JPanel Panneau_info_Partie;
    private javax.swing.JButton btn_Col_0;
    private javax.swing.JButton btn_Col_1;
    private javax.swing.JButton btn_Col_2;
    private javax.swing.JButton btn_Col_3;
    private javax.swing.JButton btn_Col_4;
    private javax.swing.JButton btn_Col_5;
    private javax.swing.JButton btn_Col_6;
    private javax.swing.JButton btn_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_J1_couleur1;
    private javax.swing.JLabel lbl_J1_desintegrateur1;
    private javax.swing.JLabel lbl_J1_nom;
    private javax.swing.JLabel lbl_J2_couleur;
    private javax.swing.JLabel lbl_J2_desintegrateur;
    private javax.swing.JLabel lbl_J2_nom;
    private javax.swing.JLabel lbl_JCourant;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField nomJoueur1;
    private javax.swing.JTextField nomJoueur2;
    // End of variables declaration//GEN-END:variables
}
